HW3
================
Chenhui Yan
2024-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(devtools)
```

    ## Loading required package: usethis

# Problem 1

## Part1: Data Cleaning:

- Retain variables: line, station, name, station latitude, longitude,
  routes served, entry, vending, entrance type, and ADA compliance.

- Convert entry to logical: The entry column has YES or NO values, so
  you’ll need to convert it into a logical TRUE/FALSE format. You can
  use functions like ifelse() or case_when() to accomplish t

``` r
# Read and clean the data
nyc_subway_data = read_csv("./dataset_hw3/hw2_prob1_dataset.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  mutate(entry = case_when(
    entry == "YES" ~ TRUE,
    entry == "NO"  ~ FALSE
  )) # Convert entry to logical TRUE/FALSE
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# View the cleaned data
nyc_subway_data
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

## Part2: A brief summary of the dataset:

The cleaned dataset contains variables such as subway line, station
name, latitude/longitude, routes served, entry status, vending, entrance
type, and ADA compliance. To clean the data, I standardized column names
using clean_names(), selected only relevant columns with select(), and
converted the entry variable from character (“YES”/“NO”) to logical
(TRUE/FALSE) using case_when(). The resulting dataset has 1868 rows and
19 columns, and it is tidy since each variable is a column, each
observation is a row, and each value is a cell.

## Part3: Answer the following questions using these data:

### How many distinct stations are there?

``` r
distinct_station = 
   nyc_subway_data %>%
  distinct(line, station_name) %>%
  nrow()
```

There are 465 distinct stations in this dataset.

### How many stations are ADA compliant?

``` r
ada_compliant =
  nyc_subway_data %>% 
  filter(ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  nrow()
```

There are 84 ADA compliant stations.

### What proportion of station entrances / exits without vending allow entrance?

``` r
proportion_no_vending_allows_entry = 
  nyc_subway_data %>%
  filter(vending == "NO") %>%  # Filter rows where there is no vending
  summarise(proportion = mean(entry == TRUE)) %>%  # Calculate the proportion where entry is TRUE
  pull(proportion)

# Output the result
proportion_no_vending_allows_entry
```

    ## [1] 0.3770492

37.7% of station entrances / exits without vending allow entrance

## Part4: Reformat data so that route number and route name are distinct variables.

``` r
nyc_subway_data_refored = 
  nyc_subway_data %>%
  mutate(across(starts_with("route"), as.character)) %>%  # Ensure all route columns are characters
  pivot_longer(
    cols = starts_with("route"), # Specify the columns for the routes
    names_to = "route_number",
    values_to = "route") %>%
  drop_na(route)# Drop rows where route is NA
nyc_subway_data_refored
```

    ## # A tibble: 4,270 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## 10 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## # ℹ 4,260 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <chr>,
    ## #   route <chr>

### How many distinct stations serve the A train?\*

``` r
nyc_subway_data_refored %>% 
  filter(route == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 60

There are distinct stations serve the A train.

### How many are ADA compliant of the stations that serve the A train?\*

``` r
nyc_subway_data_refored %>% 
  filter(ada == TRUE) %>%  
  filter(route == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 17

Of the 60 stations that serve the A train,17 have at least one ADA
compliant entry or exit.

# Problem 2

## Part1. Data Cleaning for Mr trash wheel sheet

``` r
# Specify sheet and omit non-data entries (skip rows and specify range)
mr_trash_wheel = read_excel("./dataset_hw3/hw2_prob2_datas.xlsx",
                            sheet = "Mr. Trash Wheel", 
                            skip = 1,  # Skip the first row if it's non-data or a note
                            range = "A2:N653")  # Adjust the range based on the actual data layout
# Omit rows that do not include dumpster-specific data
mr_trash_wheel_cleaned = mr_trash_wheel %>%
  filter(!is.na(Dumpster)) %>%  # Keep only rows where the 'dumpster' column is not NA
  janitor::clean_names() %>%
  select(dumpster:homes_powered) %>% 
  mutate(sports_balls = round(sports_balls, 0)) %>% 
  mutate(sports_balls = as.integer(sports_balls)) %>% 
  mutate(year = as.numeric(year)) %>% 
  mutate(trash_wheel = "mr_trash")
mr_trash_wheel_cleaned
```

    ## # A tibble: 651 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 641 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

## Part2: Data cleaning for Professor Trash Wheel sheet

``` r
pro_trash_wheel = 
  read_excel("./dataset_hw3/hw2_prob2_datas.xlsx",
             sheet = "Professor Trash Wheel",
             skip = 1,
             range = "A2:M121",) %>%
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>%
  mutate(year = as.numeric(year)) %>% 
  mutate(trash_wheel = "pro_trash")

pro_trash_wheel 
```

    ## # A tibble: 119 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 109 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

## Part3: Data cleaning for Gwynnda sheet

``` r
gwynnda_df = 
  read_excel("./dataset_hw3/hw2_prob2_datas.xlsx", 
             sheet = "Gwynnda Trash Wheel",
             skip = 1,
             range = "A2:L265", ) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>%
  mutate(trash_wheel = "gwynnda_trash") %>% 
  mutate(year = as.numeric(year))
gwynnda_df
```

    ## # A tibble: 263 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 253 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

## Part4: Combined Data

``` r
combined_trash_wheel_data = bind_rows(mr_trash_wheel_cleaned,
                                       pro_trash_wheel,
                                       gwynnda_df)
combined_trash_wheel_data
```

    ## # A tibble: 1,033 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,023 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

## A paragraph about these data

``` r
# Number of observations in the combined dataset
total_observations = nrow(combined_trash_wheel_data)

# Total weight of trash collected by Professor Trash Wheel
total_weight_prof_trash_wheel = combined_trash_wheel_data %>%
  filter(trash_wheel == "pro_trash") %>%
  summarise(total_weight = sum(weight_tons, na.rm = TRUE)) %>%
  pull(total_weight)

# Total number of cigarette butts collected by Gwynnda in June 2022
total_cig_butts_gwynnda_june_2022 = combined_trash_wheel_data %>%
  filter(trash_wheel == "gwynnda_trash", month == "June", year == 2022) %>%
  summarise(total_cig_butts = sum(cigarette_butts, na.rm = TRUE)) %>%
  pull(total_cig_butts)

# Print the results
total_observations
```

    ## [1] 1033

``` r
total_weight_prof_trash_wheel
```

    ## [1] 246.74

``` r
total_cig_butts_gwynnda_june_2022
```

    ## [1] 18120
